In [2]:
import numpy as np

In [13]:
#Array creation using list
#one dimensional array
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
#Two dimensional array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#some basic function
#dimension
b.ndim

2

In [11]:
#shape (row*column)
b.shape

(2, 3)

In [15]:
#data Type
b.dtype

dtype('int64')

In [17]:
#itemsize
b.itemsize

8

In [18]:
#size
b.size

6

In [20]:
#Number of bytes (itemsize * size)
b.nbytes

48

In [86]:
#doubt
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [87]:
b.max()

6

In [88]:
b.sum()

21

In [90]:
#axis=0 means row
#axis=1 means column
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [91]:
np.std(b)

1.707825127659933

In [23]:
# Accessing and changing the element(s)
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#r*c
#r-->0 to 1
#c-->0 to 6
c.shape

(2, 7)

In [28]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
#access the value 14
c[1,6]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


14

In [30]:
# get a list from array
#get the firt row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#get a column
c[:,2]

array([ 3, 10])

In [37]:
#re-assign the value using 
c[1,5]=20
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [40]:
#Array creation by using different function
#arange function
d=np.arange(2,100,2)
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
#using zero function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
e=np.zeros([2,3])
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#doubt
f=np.zeros([2,3,3,2])

f

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [58]:
# pass data type during creation of array
g=np.zeros(5,dtype="complex")
g

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [51]:
#using ones function
#doubt
h=np.ones((4,2,2))
h

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [78]:
h=np.ones((5,5))
h

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# all elememnt of same number

In [54]:
#using full
i=np.full((2,2),99,dtype="float32")
i

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
#full_like same size but the element can be changed a/c to second param

In [57]:
j=np.full_like(i,4)
j

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [60]:
#Random Decimal
k=np.random.rand(4,2)
k

array([[0.95410555, 0.13260937],
       [0.20475126, 0.80746663],
       [0.16871678, 0.63833033],
       [0.88920858, 0.33338397]])

In [63]:
#doubt
k=np.random.rand(4,2,3)
k

array([[[0.50375927, 0.01035331, 0.04651569],
        [0.12120266, 0.99636678, 0.82699748]],

       [[0.07363454, 0.54576039, 0.18550894],
        [0.55667329, 0.22650978, 0.13557499]],

       [[0.63867978, 0.28956973, 0.61131853],
        [0.63375611, 0.18422559, 0.00875695]],

       [[0.3102384 , 0.11044504, 0.33739301],
        [0.62485597, 0.08772178, 0.16324533]]])

In [66]:
l=np.random.random_sample(k.shape)
l

array([[[0.63261781, 0.87171997, 0.33810402],
        [0.05017349, 0.92155162, 0.53628824]],

       [[0.36747264, 0.74153923, 0.6278069 ],
        [0.75238345, 0.88478484, 0.87655446]],

       [[0.43907736, 0.12375255, 0.82584664],
        [0.70836749, 0.21818025, 0.5966675 ]],

       [[0.40898667, 0.93985686, 0.61993447],
        [0.09581816, 0.72563606, 0.38806006]]])

In [76]:
#identity matrix
m=np.identity(5, dtype="int64")
m

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [77]:
#repeat
arr=np.array([1,2,3])
n=np.repeat(arr,3,axis=0)
n

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [81]:
#linspace
p=np.linspace(1,5,5)
p

array([1., 2., 3., 4., 5.])

In [102]:
#operations --Arithmetic
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(arr2+arr2)
print(arr2-arr2)
print(arr2*arr2)
print(arr2/arr2)
print(arr1*2)

[[22 24 26 28 30]
 [32 34 36 38 40]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[121 144 169 196 225]
 [256 289 324 361 400]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [105]:
# dot product 
# r*c c*r
#ex --> 3*2 -->2,4
#doubt

In [108]:
#slicing /stacking
q=np.array([6,7,8])
q[-1]

8

In [109]:
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
for row in r:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [111]:
for cell in r.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [114]:
#reshaping
s=np.arange(6)
s

array([0, 1, 2, 3, 4, 5])

In [121]:
t=s.reshape(3,2)
t

array([[0, 1],
       [2, 3],
       [4, 5]])

In [122]:
x=s.reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [124]:
y=np.arange(6).reshape(3,2)
z=np.arange(6,12).reshape(3,2)

In [125]:
np.vstack((y,z))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [126]:
np.hstack((y,z))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [133]:
A=np.arange(30).reshape(2,15)
result=np.hsplit(A,3)
print(result)
print(result[0])
print(result[1])
print(result[2])

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [136]:
result=np.vsplit(A,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]